# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FSOAuth2.0Test' do

pod ‘AFNetworking’

end

target 'FSOAuth2.0TestTests' do

end

target 'FSOAuth2.0TestUITests' do

end

